excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://wieczorek1990.github.io/shop.soiree.tech/
title: Łukasz Wieczorek's shop
tagline: Have a many things!
description: Just sharing my thoughts…
plugins: [jekyll-paginate, kramdown]
paginate: 3
